### PR TITLE
Rename build.sh to make.sh

### PR DESCRIPTION
**Pull request by fornellas**
Long time ago this script did sttuff that calling it "build" made sense. Today, it is de facto a make wrapper, so calling for what it is, makes things easier to digest.

---

**Stack**:
- #141
- #140 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by gfechio — COMMENTED** [review]
I am not sure about this one though, although it seems like the right verb for it, it can be confused with Make as in `Makefile`, which a believe it is part of the idea but can drive a developer to wrong assumptions in oppose of `build.sh` being the common practice for Docker build or even code build in general.

**Comment by fornellas** [comment]
@gfechio `make_wrapper.sh`?

**Comment by fornellas** [comment]
PS: I did got confused comments about the name build and it being a make wrapper, which motivated me to cut this PR. But you do have a point as well.

**Comment by gfechio** [comment]
Considering Mage, let's leave as is, no ?

**Pull request closed without merging**
